Repository ScribeLabsAI/ScribeAuth, pull requests merged in 2023-11, with the labels that each got.

#101 feat: add mfa support
  .github/workflows/test.yml
  requirements.txt
  scribeauth/__init__.py
  scribeauth/__main__.py
  scribeauth/scribeauth.py
  tests/test_scribeauth.py
Labels: enhancement

#94 chore(master): release 1.1.0
  CHANGELOG.md
  setup.py
Labels: autorelease: pending

#109 chore(master): release 1.1.1
  CHANGELOG.md
  setup.py
Labels: autorelease: pending

#103 feat: create documentation to be published in ScribeLabs/documentation repo
  .github/workflows/update-doc.yml
  docs_source/conf.py
  docs_source/reference.rst
  scribeauth/scribeauth.py
Labels: documentation

#122 Update yaml
  .github/workflows/update-doc.yml
Labels: bug, enhancement

#115 chore(master): release 1.2.0
  CHANGELOG.md
  setup.py
Labels: autorelease: pending
